### PR TITLE
add multiple categories support

### PR DESCRIPTION
**Pull request by zilongshanren**

### CODE REVIEW

**Comment by zilongshanren** [comment]
Just as mentioned in https://github.com/jekyll/jekyll/issues/3930
They Jeklly team never implemented the space separated feature for multiple categories and multiple tags.

So this PR is the fix.

**Comment by zilongshanren** [comment]
@yoshinari-nomura  Really wired, since comma separated string are supported.
So my previous PR might be wrong if users use comma separated string as tags and categories.
What do you think about it?

**Comment by zilongshanren** [comment]
@yoshinari-nomura 
I have tested on Hexo, it only supports YAML list format, neither the comma separated nor the space separated categories and tags are supported.

So I think in order to keep the usage across multiple platform, we should add documents to org-octopress.

```
The space separated categories and tags are supported.
```

thanks.

**Comment by yoshinari-nomura** [comment]
Thanks a lot.
> The space separated categories and tags are supported.
I'll add some document to README later.

**Pull request merged**
